<?php
// Automatically generated by TestLink installer (except the closing line)
// Still fails to write it.
// values are ,of course, to be changed.
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', 'testlink');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
?>
